import Navbar from '../components/Navbar'
import Link from 'next/link'

const steps = [
  {
    num: '01',
    icon: '📝',
    title: 'NOMINATE YOUR TOKEN',
    color: '#00d9f5',
    desc: 'Submit your Solana token\'s contract address. The site automatically fetches the token name, ticker, logo, and current market cap from DexScreener. Nomination is completely free.'
  },
  {
    num: '02',
    icon: '🗳️',
    title: 'EARN 50 VOTES',
    color: '#a855f7',
    desc: 'Share your token\'s nomination link with your community. Any visitor can vote — no wallet connection or account required. Each IP address gets one vote per token. Once your token reaches 50 votes, it automatically joins the race queue.'
  },
  {
    num: '03',
    icon: '🏁',
    title: 'RACE BEGINS',
    color: '#ffb800',
    desc: 'When 10 tokens are in the queue, the race starts automatically. Each race lasts exactly 4 hours. The site tracks each token\'s market cap in real-time, updating every 30 seconds via DexScreener data.'
  },
  {
    num: '04',
    icon: '📊',
    title: 'WATCH THE CHART',
    color: '#00f5a0',
    desc: 'The live race chart shows all 10 tokens racing to the highest market cap. Rankings update in real-time. If a token\'s market cap drops more than 95% from its starting value, it is flagged as rugged and disqualified from the final standings.'
  },
  {
    num: '05',
    icon: '🏆',
    title: 'WINNER CROWNED',
    color: '#ffb800',
    desc: 'After 4 hours, the token with the highest market cap wins the race. The winner is immortalized in the Hall of Fame and declared the official PUMPRACE Treasury Token.'
  },
  {
    num: '06',
    icon: '💰',
    title: 'TREASURY DISTRIBUTION',
    color: '#ff3d6b',
    desc: 'All platform fees generated by PUMPRACE during the race period are manually distributed to the winning token\'s community treasury wallet. This is announced publicly after each race. The next race begins automatically once 10 new tokens qualify.'
  }
]

const rules = [
  'Token must be on Solana and have an active listing on DexScreener',
  'Minimum market cap required at time of nomination',
  '1 vote per IP address per token — no bot voting',
  'All 10 race slots are filled first-come-first-served from the vote queue',
  'A token that loses 95%+ of its starting market cap is disqualified as rugged',
  'Rugged tokens are ranked last regardless of final market cap',
  'The race lasts exactly 4 hours from start time — no extensions',
  'Market cap data is sourced from DexScreener — final mcap at race end determines winner',
  'Treasury distribution is manual and at the discretion of the PUMPRACE team',
  'PUMPRACE is not responsible for token price movements — this is for fun only'
]

export default function HowItWorksPage() {
  return (
    <>
      <Navbar />
      <div className="page-wrap" style={{ paddingTop: 28 }}>

        {/* HERO */}
        <div style={{ textAlign: 'center', marginBottom: 48 }}>
          <div className="section-label" style={{ display: 'flex', justifyContent: 'center', marginBottom: 12 }}>
            ◈ THE RULEBOOK
          </div>
          <h1 style={{ fontSize: 28, letterSpacing: 4, marginBottom: 12 }}>HOW IT WORKS</h1>
          <p style={{ color: 'var(--text2)', fontSize: 14, maxWidth: 540, margin: '0 auto', lineHeight: 1.8 }}>
            PUMP RACE is the ultimate Solana market cap battle arena.
            Nominate your token, build community support, and race to the top.
          </p>
        </div>

        {/* STEPS */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16, marginBottom: 48 }}>
          {steps.map((step, i) => (
            <div key={i} className="card fade-in-up" style={{
              display: 'flex',
              gap: 20,
              alignItems: 'flex-start',
              animationDelay: `${i * 0.06}s`,
              borderLeft: `3px solid ${step.color}`
            }}>
              <div style={{
                fontFamily: 'var(--font-display)',
                fontSize: 32,
                fontWeight: 900,
                color: step.color,
                opacity: 0.25,
                lineHeight: 1,
                flexShrink: 0,
                minWidth: 48
              }}>
                {step.num}
              </div>
              <div style={{ fontSize: 28, flexShrink: 0 }}>{step.icon}</div>
              <div>
                <div style={{
                  fontFamily: 'var(--font-display)',
                  fontSize: 13,
                  fontWeight: 700,
                  color: step.color,
                  letterSpacing: 2,
                  marginBottom: 8
                }}>
                  {step.title}
                </div>
                <div style={{ fontSize: 13, color: 'var(--text2)', lineHeight: 1.8 }}>
                  {step.desc}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* TREASURY SECTION */}
        <div className="card fade-in" style={{
          background: 'linear-gradient(135deg, rgba(255,61,107,0.06), rgba(168,85,247,0.06))',
          border: '1px solid rgba(255,61,107,0.2)',
          marginBottom: 32,
          padding: '28px 24px'
        }}>
          <div style={{ display: 'flex', gap: 16, alignItems: 'flex-start', flexWrap: 'wrap' }}>
            <div style={{ fontSize: 40 }}>💎</div>
            <div>
              <div style={{
                fontFamily: 'var(--font-display)',
                fontSize: 14,
                color: 'var(--danger)',
                letterSpacing: 3,
                marginBottom: 10
              }}>
                TREASURY SYSTEM — IMPORTANT
              </div>
              <div style={{ fontSize: 13, color: 'var(--text2)', lineHeight: 1.9 }}>
                The <strong style={{ color: 'var(--text)' }}>treasury distribution is handled manually</strong>, not via smart contract.
                After each race, the PUMPRACE team publicly announces the winner and distributes accumulated platform fees
                to the winning token's designated treasury wallet.<br /><br />
                This system relies on <strong style={{ color: 'var(--text)' }}>community trust and transparency</strong>.
                All distributions are announced publicly with transaction hashes so the community can verify on-chain.
                As PUMPRACE grows, this process may be automated via smart contract in the future.<br /><br />
                <span style={{ color: 'var(--warn)' }}>
                  ⚠️ PUMPRACE is a community experiment. Never invest more than you can afford to lose.
                  Token prices are driven by market forces — PUMPRACE does not manipulate prices.
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* RULES */}
        <div className="card fade-in" style={{ marginBottom: 40 }}>
          <div className="section-label" style={{ marginBottom: 16 }}>◈ OFFICIAL RULES</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {rules.map((rule, i) => (
              <div key={i} style={{
                display: 'flex',
                gap: 12,
                fontSize: 12,
                color: 'var(--text2)',
                lineHeight: 1.6,
                padding: '8px 0',
                borderBottom: i < rules.length - 1 ? '1px solid var(--border)' : 'none'
              }}>
                <span style={{ color: 'var(--accent)', flexShrink: 0, fontWeight: 700 }}>{String(i + 1).padStart(2, '0')}.</span>
                {rule}
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div style={{ textAlign: 'center', paddingBottom: 20 }}>
          <div style={{ fontSize: 10, letterSpacing: 3, color: 'var(--muted)', marginBottom: 16 }}>
            READY TO RACE?
          </div>
          <Link href="/nominate" className="btn btn-primary" style={{ fontSize: 13, padding: '14px 32px' }}>
            NOMINATE YOUR TOKEN →
          </Link>
        </div>
      </div>
    </>
  )
}
